# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dish_scan_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(672, 272)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(Frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 4)
        self.pushButton_3 = QtWidgets.QPushButton(Frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 5, 3, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(Frame)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 10, 3, 3, 1)
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 13, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 3, 4)
        self.comboBox = QtWidgets.QComboBox(Frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 14, 0, 1, 4)
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 3, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(Frame)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 10, 0, 3, 2)
        self.checkBox = QtWidgets.QCheckBox(Frame)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 10, 2, 3, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 3, 2)
        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 3, 1)
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 3, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_6.setText(_translate("Frame", "Scan Time Period(s): "))
        self.label_8.setText(_translate("Frame", "Mention IDs of the wells to be imaged as a string separated by commas without spaces. For eg. 1-5,8,9"))
        self.pushButton_3.setText(_translate("Frame", "Current Position As Home"))
        self.checkBox_2.setText(_translate("Frame", "Scan Save"))
        self.label_4.setText(_translate("Frame", "Scan Save: Scan for animal and only save image along with coordinates if an animal is seen."))
        self.label_3.setText(_translate("Frame", "Dish Template (write well IDs):"))
        self.label_7.setText(_translate("Frame", "Well IDs are counted from top left corner as the origin of the plate."))
        self.comboBox.setItemText(0, _translate("Frame", "9 Pelco 50 mm Dishes"))
        self.comboBox.setItemText(1, _translate("Frame", "9 Pelco 30 mm Dishes"))
        self.comboBox.setItemText(2, _translate("Frame", "6 Well Plate"))
        self.comboBox.setItemText(3, _translate("Frame", "12 Well Plate"))
        self.comboBox.setItemText(4, _translate("Frame", "24 Well Plate"))
        self.comboBox.setItemText(5, _translate("Frame", "96 Well Plate"))
        self.label_2.setText(_translate("Frame", "Experiment ID:"))
        self.label_5.setText(_translate("Frame", "The animal is centered in the frame before taking the image. If not selected all images are saved"))
        self.pushButton_2.setText(_translate("Frame", "Start Acquisition"))
        self.checkBox_3.setText(_translate("Frame", "Substrate Illumination On"))
        self.checkBox.setText(_translate("Frame", "Turn off when not scanning"))
        self.label.setText(_translate("Frame", "Saving Path:"))
        self.pushButton.setText(_translate("Frame", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

